version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: car-speed-detection
    versions:
    - 0.7.5
    - 0.7.6
    - 0.7.7
  - dependency-name: google-auth
    versions:
    - 1.29.0
  - dependency-name: pandas
    versions:
    - 1.2.2
    - 1.2.3
  - dependency-name: matplotlib
    versions:
    - 3.4.0
  - dependency-name: numpy
    versions:
    - 1.20.1
